#! /bin/python

import sys
import re
import subprocess


if len(sys.argv) < 2:                                   
    print("ERROR: NOT ENOUGH ARGUMENTS")              
    print("Syntax: playit \"link\" [resolution]\n\n")
elif len(sys.argv) == 2:
    resolution = "360p"  # If no resolution argument is passed, resolution defaults to 360p.
else:
    resolution = str(sys.argv[2])  # In some cases, the desired resolution isn't available.
                                   # The script has no way of handling this yet.


m = re.search('watch.*', str(sys.argv[1]))
vid_id = str(m.group(0))

proc = subprocess.Popen(["curl", "http://playit.pk/"+vid_id], stdout=subprocess.PIPE)
out = proc.communicate()

m = re.search(resolution+'.*(mp4|webm)', str(out))
m = re.search('http.*?(?="\ type)', str(m.group(0))) 
stream_url = str(m.group(0))

subprocess.call(["mplayer", stream_url]) # The streaming url can passed to any media player that supports it.
